FROM python:3.11-slim

WORKDIR /frontend

COPY requirements_frontend.txt .
RUN pip install --no-cache-dir -r requirements_frontend.txt --root-user-action=ignore

COPY ./frontend .

CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]

