FROM python:3.11-slim

WORKDIR /backend

COPY requirements_backend.txt .
RUN pip install --no-cache-dir -r requirements_backend.txt --root-user-action=ignore

COPY ./backend .

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]