version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: secureprompt_backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=secureprompt
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: secureprompt_frontend
    environment:
      - SECUREPROMPT_API=http://backend:8000/api/v1
    ports:
      - "8501:8501"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: secureprompt_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data:
